FROM node:16-alpine

WORKDIR /app

COPY frontend/package* ./frontend/

RUN npm install --force --prefix ./frontend

COPY frontend ./frontend

RUN npm run build --prefix ./frontend

RUN npm install -g serve

EXPOSE 3000

CMD ["sh", "-c", " npx serve -s /app/frontend/build -l 3000"]
